### PR TITLE
Set embedded ASP default language to VB

### LINKED ISSUE #5677: JSP syntax highlighting broke
### Description of the Issue
In the latest release, JSP syntax highlighting changed.

Code blocks between `<%` and `%>`, and `<%=` and `%>`, used to be light blue. Now they are white, the same as everything else, so they are much less distinguished.

I am not entirely sure I'm describing _what_ used to be light blue correctly. I just know there's no light blue anymore, and I'm very used to it.

I don't see any mention of syntax highlighting changes in the changelog, so this must be inadvertent. Maybe it's a side effect of the Scintilla upgrade? Either way, I'd really appreciate getting the old syntax highlighting (or some similar visual distinction for `<%…%>` and `<%= … %>` code blocks) back.

If it would help, I can provide screenshots of the new behavior, and if really necessary I can also try installing an old version and showing how that looked.

### Steps to Reproduce the Issue
1. Open a JSP file (with JSP syntax highlighting enabled)

### Expected Behavior
Code blocks would be highlighted in light blue.

### Actual Behavior
Code blocks have no background or other visual distinction throughout them (just a yellow background on the `<%`, `<%=`, and `%>` tags themselves).

### Debug Information
```
Notepad++ v7.7   (64-bit)
Build time : May 19 2019 - 13:05:35
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppFTP.dll 
```

### LINKED ISSUE #5702: Style configuration not working properly - Notepad++ 7.7
### Style configuration not working for ASP files

I've just updated to **7.7** version and some custom styles that I defined to ASP/VBScript language aren't working anymore. I reverted to **7.6.6** and everything works just fine.

### Reproducing the Issue
Using the version **7.7**, set your custom style to **ASP** extension:
image

### Expected Behavior
It should use your defined styles.

### Actual Behavior
It just ignores everything I have set in styles.

### Debug Information
Notepad++ v7.7   (32-bit)
Build time : May 19 2019 - 13:08:20
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll LuaScript.dll mimeTools.dll NppConverter.dll NppExport.dll

### PR DESCRIPTION
**Pull request by dail8859**
Closes #5702, Closes #5677

See also: https://notepad-plus-plus.org/community/topic/17696/bug-problem-with-syntax-highlighting-not-working-on-asp-classic-scripts

### CODE REVIEW

File: PowerEditor/src/ScitillaComponent/ScintillaEditView.cpp [hunk 1]
```diff
@@ -745,6 +745,8 @@ void ScintillaEditView::setEmbeddedAspLexer()
 		keywordList = wstring2string(kwlW, CP_ACP);
 	}
 
+	execute(SCI_SETPROPERTY, reinterpret_cast<WPARAM>("asp.default.language"), reinterpret_cast<LPARAM>("2"));
+
 	execute(SCI_SETKEYWORDS, 2, reinterpret_cast<LPARAM>(getCompleteKeywordList(keywordList, L_VB, LANG_INDEX_INSTR)));
```
Comment (donho) [inline PowerEditor/src/ScitillaComponent/ScintillaEditView.cpp]: It looks better what I have tried to fix in SciLexer.dll.
However what's the meaning of value "2" on "asp.default.language" for `SCI_SETPROPERTY` ?

Comment (dail8859) [reply PowerEditor/src/ScitillaComponent/ScintillaEditView.cpp]: 2 is `eScriptVBS` in LexHTML.cxx

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/1a76bd591370cf86a3b041d7ceb5bf534cc4d9b8/scintilla/lexers/LexHTML.cxx#L38
